computer science/Final Project/project/app/forms/event_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, DateTimeField
from wtforms.validators import DataRequired
from app.models import Category
from datetime import datetime


class CategoryForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    save = SubmitField('Save')

class EventForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    header = TextAreaField('Header')
    description = TextAreaField('Description')
    date = DateTimeField('Fecha y Hora', default=datetime.utcnow, format='%Y-%m-%d %H:%M:%S', validators=[DataRequired()])
    category = SelectField('Category', coerce=int, validators=[DataRequired()])
    save_and_view = SubmitField('Save and View')
    save = SubmitField('Save')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name) for category in Category.query.all()]
  

computer science/Final Project/project/app/forms/user_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, PasswordField, SelectField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from app.models import Role

class RegisterForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])
    confirmation = PasswordField('Repeat password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

class LoginForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class UserForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    role = SelectField('Role', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Save')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name) for role in Role.query.all()]
  

computer science/Final Project/project/app/routes/comment_routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from app.forms import EventForm, EventOccurrenceForm, CommentForm
from app.models import Comment
from flask_login import current_user
from app.helpers import requires_access_level
from app import db
from datetime import datetime
import string

comment_bp = Blueprint('comment', __name__)


@comment_bp.route('/event/<int:event_id>/comment', methods=['POST'])
@requires_access_level('viewer')
def create_comment(event_id):
    form = CommentForm()

    # Validate form and create Comment with form data
    if form.validate_on_submit():
        new_comment = Comment(
            text=form.text.data,
            date_time=(datetime.now()),
            id_event=event_id,
            id_user=current_user.id
            
        )

        # Add the session new comment and commit the changes to the database
        db.session.add(new_comment)
        db.session.commit()
        
        # Success create message
        flash('Comment created successfully.', 'success')
        #return redirect(url_for('event.view_event', event_id=event_id))
    
    return redirect(url_for('event.view_event', event_id=event_id))

@comment_bp.route('/event/<int:event_id>/delete_comment/<int:comment_id>', methods=['POST'])
@requires_access_level('journalist')
def delete_comment(event_id, comment_id):
    # Get comment by ID
    comment = Comment.query.get_or_404(comment_id)  

    # Delete the session comment and commit the changes to the database
    db.session.delete(comment)  
    db.session.commit()  

    # Success message and Redirect to main page or wherever you want
    flash('Comment successfully deleted.', 'success')  
    return redirect(url_for('event.view_event', event_id=event_id)) 

@comment_bp.route('/more_comments')
def more_commnets():
    # Get page and event request parameter
    page = request.args.get('page', 0, type=int)
    event_id = request.args.get('event', 0, type=int)

    # Get the next 10 comments
    more_comments = Comment.query.filter_by(id_event=event_id).order_by(Comment.date_time.desc()).limit(10).offset(page * 10).all()
    has_more = len(more_comments) == 10
    
    return render_template('partial_comments.html', event_id=event_id, comments=more_comments, has_more=has_more)

computer science/Final Project/project/app/routes/event_routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.forms import EventForm, CommentForm, CategoryForm
from app.models import Event, Category, EventOccurrence, Comment, SurveyResponse
from flask_login import current_user
from app.helpers import requires_access_level
import markdown
from app import db

event_bp = Blueprint('event', __name__)


@event_bp.route('/category/<int:category_id>')
def category_events(category_id):
    category = Category.query.get(category_id)
    # Get all events from the database order by for date
    events = Event.query.filter_by(id_category=category_id).all()
    return render_template('category.html', category=category, events=events)  


@event_bp.route('/create_category', methods=["GET", "POST"])
@requires_access_level('journalist')
def create_category():
    form = CategoryForm()

    # Validate form and create Category with form data
    if form.validate_on_submit():
        new_category = Category(
            name=form.name.data
        )

        # Add the session new category and commit the changes to the database
        db.session.add(new_category)
        db.session.commit()

        # Success create message and redirect home page
        flash('Category created successfully.', 'success')
        
        return redirect(url_for('event.list_events'))
    
    # Render create form
    return render_template('update_category.html', form=form)

@event_bp.route('/delete_category/<int:category_id>', methods=['POST'])
@requires_access_level('journalist')
def delete_category(category_id):
    # Get the category by ID
    category = Category.query.get_or_404(category_id) 

    # Delete the category from the session and Commit the changes to the database
    db.session.delete(category)
    db.session.commit()

    # Success delete message and Redirect list events templates
    flash('Category successfully deleted.', 'success')
    return redirect(url_for('event.list_events'))










@event_bp.route('/')
def index():
    # Get all events from the database order by for date
    events = Event.query.order_by(Event.date.desc()).all()  
    return render_template('index.html', events=events) 

@event_bp.route('/events')
def list_events():
    categories = Category.query.all()
    # Get all events from the database order by for date
    events = Event.query.order_by(Event.date.desc()).all()
    return render_template('events.html', categories=categories, events=events)  

@event_bp.route('/create_event', methods=["GET", "POST"])
@requires_access_level('journalist')
def create_event():
    form = EventForm()

    # Validate form and create Event with form data
    if form.validate_on_submit():
        new_event = Event(
            name=form.name.data,
            header=form.header.data,
            description=form.description.data,
            date=form.date.data,
            id_user_creator=current_user.id,
            id_category=form.category.data 
        )


        # Add the session new event and commit the changes to the database
        db.session.add(new_event)
        db.session.commit()

        # Success create message and redirect home page
        flash('Event created successfully.', 'success')
        
        # Check press button
        if form.save_and_view.data:
            return redirect(url_for('event.view_event', event_id=new_event.id))  # Redirige a la siguiente etapa
        
        return redirect(url_for('event.list_events'))
    
    # Render create form
    title = "Create Event"
    return render_template('update_event.html', title=title, form=form)

@event_bp.route('/edit_event/<int:event_id>', methods=['GET', 'POST'])
@requires_access_level('journalist')
def edit_event(event_id):
    # Get the event by ID and Load event data into the form
    event = Event.query.get_or_404(event_id) 
    form = EventForm(obj=event)
    
    # Valid edit form
    if form.validate_on_submit():
        # Update event attributes with form data
        event.name = form.name.data
        event.header = form.header.data
        event.description = form.description.data
        event.date = form.date.data
        event.id_category = form.category.data

        # Save changes to the database
        db.session.commit()  

        # Success updated message and Redirect list events templates
        flash('Event updated successfully.', 'success')

        # Check press button
        if form.save_and_view.data:
            return redirect(url_for('event.view_event', event_id=event.id))  # Redirige a la siguiente etapa
        
        return redirect(url_for('event.list_events'))  
    
    # Update select field of form with event value
    form.category.data = event.id_category
    
    # Render Edit form
    title = "Edit Event"
    return render_template('update_event.html', title=title, form=form)


@event_bp.route('/delete_event/<int:event_id>', methods=['POST'])
@requires_access_level('journalist')
def delete_event(event_id):
    # Get the event by ID
    event = Event.query.get_or_404(event_id) 

    # Delete the event from the session and Commit the changes to the database
    db.session.delete(event)
    db.session.commit()

    # Success delete message and Redirect list events templates
    flash('Event successfully deleted.', 'success')
    return redirect(url_for('event.list_events'))

@event_bp.route('/view_event/<int:event_id>')
def view_event(event_id):
    # Get event by ID
    event = Event.query.get_or_404(event_id)  
    
    # Get all event occurrences from the database
    ocurrences = EventOccurrence.query.filter_by(id_event=event_id).order_by(EventOccurrence.date_time.desc()).all()
    
    # Get first 10 comments from the database
    comments = Comment.query.filter_by(id_event=event_id).order_by(Comment.date_time.desc()).limit(10).offset(0).all()
    has_more = len(comments) == 10

    # Convert header and description event field in html with markdown
    event.mheader = markdown.markdown(event.header)
    event.mdescription = markdown.markdown(event.description)

    cform = CommentForm()
    
    # Run ocurrence to covert text in hmtl wit markdown and count total vote
    for ocurrence in ocurrences:
        ocurrence.mtext = markdown.markdown(ocurrence.text)
        ocurrence.vote = False
        ocurrence.total_vote = sum(len(o.responses) for o in ocurrence.options)

        # Determine if the user has already voted for one of the options in the survey or not.
        if ocurrence.ocurrence_type.value == "survey":
            try:
                exist = SurveyResponse.query.filter_by(id_survey=ocurrence.id, id_user=current_user.id).all()
                if len(exist) > 0:
                    ocurrence.vote = True
            except AttributeError:
                #if not login (current_user.id error) pass
                pass
    
    # Show event view template
    return render_template('view_event.html', event=event, ocurrences=ocurrences, comments=comments, has_more=has_more, page=0, cform=cform)  # Pasa la lista de eventos a la plantilla

computer science/Final Project/project/app/routes/user_routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from werkzeug.security import check_password_hash, generate_password_hash
from app.forms import LoginForm, RegisterForm, UserForm
from app.models import User, Role
from app.helpers import requires_access_level
from flask_login import login_user, logout_user, login_required
from flask_login import current_user
from app import db
#from helpers import login_required

user_bp = Blueprint('user', __name__)


@user_bp.route('/users/<int:user_id>')
def user_detail(user_id):
    # Aquí iría la lógica para mostrar los detalles de un usuario
    return render_template('user_detail.html', user_id=user_id)




"""
    if form.validate_on_submit():
        name = form.name.data
        new_greeting = Greeting(name=name)
        db.session.add(new_greeting)
        db.session.commit()
        flash(f'¡Hola, {name}!')
        return redirect(url_for('index'))
    return render_template('index.html', form=form)
"""

@user_bp.route('/login', methods=["GET", "POST"])
def login():
    """Log user in"""
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(name=form.name.data).first()
        
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('Successful login.', 'success')
            
            return redirect(request.args.get("next") or url_for("event.index"))
        else:
            flash('Incorrect email or password.', 'danger')
    else:
        print(form.errors)
    return render_template('login.html', form=form)


@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have successfully logged out.', 'success')
    return redirect(url_for('event.index'))


@user_bp.route('/register', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).first():
            flash('The email is already registered. Choose another.', 'warning')
            return redirect(url_for('user.register'))
        if User.query.filter_by(name=form.name.data).first():
            flash('The username is already registered. Choose another.', 'warning')
            return redirect(url_for('user.register'))
        
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        default_role = Role.query.first()
        new_user = User(name=form.name.data, email=form.email.data, password=hashed_password, id_role=default_role.id)
        
        db.session.add(new_user)
        db.session.commit()
        
        flash('Successful registration. Now you can log in.', 'success')
        return redirect(url_for('user.login'))
    
    return render_template('register.html', form=form)


@user_bp.route('/users')
@requires_access_level('administrator')
@login_required
def list_users():
    users = User.query.all()  # Obtiene todos los eventos de la base de datos
    return render_template('users.html', users=users)  # Pasa la lista de eventos a la plantilla


@user_bp.route('/edit_user/<int:user_id>', methods=['GET', 'POST'])
@requires_access_level('administrator')
@login_required
def edit_user(user_id):
    # Get user by ID and load data into form
    user = User.query.get_or_404(user_id)  
    form = UserForm(obj=user)

    if form.validate_on_submit():
        if form.email.data != user.email and User.query.filter_by(email=form.email.data).first():
            flash('The email is already registered. Choose another.', 'warning')
            return redirect(url_for('user.register'))
        if form.name.data != user.name and User.query.filter_by(name=form.name.data).first():
            flash('The username is already registered. Choose another.', 'warning')
            return redirect(url_for('user.register'))

        # Update event attributes with form data
        user.name = form.name.data
        user.email = form.email.data
        user.id_role = form.role.data
        
        # Save changes to the database
        db.session.commit() 
        

        flash('User updated successfully.', 'success')
        return redirect(url_for('user.list_users'))  
    
    form.role.data = user.id_role

    return render_template('update_user.html', form=form)

@user_bp.route('/delete_user/<int:user_id>', methods=['POST'])
@requires_access_level('administrator')
@login_required
def delete_user(user_id):
    if current_user.id == user_id:
        flash('You dont can delete yourself.', 'warning')
        return redirect(url_for('user.list_users'))
    
    # Get user by ID
    user = User.query.get_or_404(user_id)
    
    # Delete user of session and Save changes to the database
    db.session.delete(user)
    db.session.commit()

    flash('User successfully deleted.', 'success')
    return redirect(url_for('user.list_users')) 


@user_bp.route('/view_user/<int:user_id>')
@requires_access_level('administrator')
@login_required
def view_user(user_id):
    # Get user by ID
    user = User.query.get_or_404(user_id)
    
    return render_template('view_user.html', user=user)

computer science/Final Project/project/app/templates/category.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1>Category: {{category.name}}</h1>

{% for event in events %}
<div class="mt-3 bg-light">
    <div class="pb-3 pt-3">
<a href="{{ url_for('event.view_event', event_id=event.id) }}"><h2>{{ event.name }}</h2></a>
</div>
</div>        

{% else %}
<tr>
    <td colspan="3">No events available</td>
</tr>
{% endfor %}

{% endblock %}

computer science/Final Project/project/app/templates/events.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1>Categories</h1>

<!-- Button for create category -->
<div class="row mb-3">
    <div class="col text-end"><a class="btn btn-primary" href="{{ url_for('event.create_category')}}">Create
            Category</a>
    </div>
</div>

<!-- list of categories with delete button -->
<div class="row">
    <div class="col text-start">
        {% for category in categories %}
        <span class="btn btn-info btn-sm"><strong>{{category.name}}</strong>
            <form action="{{ url_for('event.delete_category', category_id=category.id) }}" method="POST"
                style="display:inline;">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button class="btn btn-secondary btn-sm ms-3" type="submit"
                    onclick="return confirm('Are you sure you want to delete this category?');">X</button>
            </form>
        </span>
        {% endfor %}
    </div>
</div>

<hr class="mt-3 mb-3">


<h1>Event List</h1>

<!-- Button for create event -->
<div class="row mb-3">
    <div class="col text-end"><a class="btn btn-primary" href="{{ url_for('event.create_event')}}">Create
            Event</a>
    </div>
</div>
<!-- Table of events with button for view, edit and delete -->
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for event in events %}
        <tr>
            <th scope="row">{{ event.id }}</th>
            <td>{{ event.name }}</td>
            <td>{{ event.date }}</td>
            <td><a class="btn btn-primary" href="{{ url_for('event.view_event', event_id=event.id) }}">View</a>
                <a class="btn btn-secondary" href="{{ url_for('event.edit_event', event_id=event.id) }}">Edit</a>
                <form action="{{ url_for('event.delete_event', event_id=event.id) }}" method="POST"
                    style="display:inline;">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <button class="btn btn-danger" type="submit"
                        onclick="return confirm('Are you sure you want to delete this event?');">Delete</button>
                </form>
            </td>

        </tr>
        {% else %}
        <tr>
            <td colspan="3">No events available.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

computer science/Final Project/project/app/templates/index.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1>Event List</h1>

<!-- list of events -->
{% for event in events %}
<div class="mt-3 bg-light ps-3">
    <div class="pt-3 text-start">
        <a class="btn btn-sm btn-danger" href="{{ url_for('event.category_events', category_id=event.category.id) }}">
            {{ event.category.name }}
        </a>
    </div>
    <div class="pb-3 text-start">
        <a href="{{ url_for('event.view_event', event_id=event.id) }}">
            <h2>{{ event.name }}</h2>
        </a>
    </div>
</div>

{% else %}
<tr>
    <td colspan="3">No events available</td>
</tr>
{% endfor %}

{% endblock %}

computer science/Final Project/project/app/templates/layout.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">

    <!-- http://getbootstrap.com/docs/5.3/ -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- https://favicon.io/emoji-favicons/money-bag/ -->
    <!--link href="/static/favicon.ico" rel="icon"-->

    <script src="/static/bootstrap.bundle.min.js"></script>
    <link href="/static/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/styles.css" rel="stylesheet">

    <title>Events: {% block title %}{% endblock %}</title>

</head>

<body>

    <nav class="bg-light border navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Events</a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if current_user.is_authenticated %}
                <ul class="navbar-nav me-auto mt-2">
                    {% if current_user.role.name in ['journalist', 'administrator'] %}
                    <li class="nav-item"><a class="nav-link" href="/events">Events</a></li>
                    <li class="nav-item"><a class="nav-link" href="/create_event">Add Event</a></li>
                    {% endif %}
                    {% if current_user.role.name in ['administrator'] %}
                    <li class="nav-item"><a class="nav-link" href="/users">Users</a></li>
                    {% endif %}
                    
                </ul>
                <ul class="navbar-nav ms-auto mt-2">
                    <li class="nav-item pt-2 pb-2"><strong style="color: grey;">User: {{current_user.name}}</strong></li>
                    <li class="nav-item"><a class="nav-link" href="/logout">Log Out</a></li>
                </ul>
                {% else %}
                <ul class="navbar-nav ms-auto mt-2">
                    <li class="nav-item"><a class="nav-link" href="/register">Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="/login">Log In</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    {% if get_flashed_messages() %}
    <header>
        <div class="alert alert-primary mb-0 text-center" role="alert">
            {{ get_flashed_messages() | join(" ") }}
        </div>
    </header>
    {% endif %}
    {% block header %}{% endblock %}

    <main class="container py-3 text-center">
        {% block main %}{% endblock %}
    </main>

    <footer class="mb-5">
        <p class="mb-3 small text-center text-muted">
            Events
        </p>
    </footer>
    {% block javascript %}{% endblock %}
</body>

</html>

computer science/Final Project/project/app/templates/partial_comments.html
{% for comment in comments %}
<div class="comment">
    <div class="row">
        <div class="col">
            <div class="text-start ps-5">{{comment.user.name}}</div>
            <div class="text-start ps-5" style="font-size: 10px;">{{comment.date_time.strftime('%Y-%m-%d | %H:%M')}}
            </div>
        </div>
        <div class="col" style="text-align: end;">
            <div class="ps-5" style="font-size: 30px; color: grey;"># {{comment.id}}</div>
        </div>
    </div>

    <div class="text-start ps-5 pt-3">{{comment.text}}
    </div>
    <div style="text-align: end;">
        <form action="{{ url_for('comment.delete_comment', event_id=event_id, comment_id=comment.id) }}" method="POST"
            style="display:inline;">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="btn btn-link" type="submit"
                onclick="return confirm('Are you sure you want to delete this comment?');">Delete</button>
        </form>
        <hr>
    </div>
</div>
{% endfor %}

computer science/Final Project/project/app/templates/register.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}

<!-- Register form -->
<h1>Register</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mt-2">
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mt-2">
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mt-2">
            {{ form.confirmation.label }}<br>
            {{ form.confirmation(size=32) }}<br>
            {% for error in form.confirmation.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mt-2">
            {{ form.submit() }}
        </div>
    </form>

{% endblock %}

computer science/Final Project/project/app/templates/survey.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1>Survey</h1>


{% if current_user.is_authenticated %}

<!-- Survey list of option with button for vote -->
<div class="vote text-start">
    {{ocurrence.text}}
    <div class="text-start mt-2 mb-5">
        {% for o in ocurrence.options %}
        <div class="mb-1">

            <form
                action="{{ url_for('ocurrence.vote', event_id=ocurrence.event.id, ocurrence_id=ocurrence.id, option_id=o.id) }}"
                method="POST" style="display:inline;">
                <input name="csrf_token" type="hidden" value="{{ csrf_token() }}" />
                <button class="btn btn-outline-primary btn-sm" style="border-radius: 40%;" type="submit">O</button>
            </form>
            {{o.option}}
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-secondary" href="{{ url_for('event.view_event', event_id=event_id) }}">Back</a>

</div>
{% else %}
<h2>For vote</h2>
<a class="btn btn-primary" href="{{ url_for('user.login') }}">Login</a>

{% endif %}

{% endblock %}

computer science/Final Project/project/app/templates/update_category.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1 class="mb-5">Create Category</h1>

<!-- Category create form -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group row mb-3">

        {{ form.name.label(class="form-label col-sm-2 col-form-label") }}
        {{ form.name(class="form-control col", size=32) }}
        {% for error in form.name.errors %}
        <span class="col-sm-10 offset-sm-2" style="color: red;">[{{ error }}]</span>
        {% endfor %}

    </div>
    
    <div class="row">
        
        <div class="col">
            {{ form.save(class="btn btn-primary") }}
            <a class="btn btn-secondary" href="{{ url_for('event.list_events') }}">Cancel</a>

        </div>
        
    </div>
</form>
{% endblock %}

computer science/Final Project/project/app/templates/update_user.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1>Edit User</h1>

<!-- Edit user form -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group row mb-3">

        {{ form.name.label(class="form-label col-sm-2 col-form-label") }}
        {{ form.name(class="form-control col", size=32) }}
        {% for error in form.name.errors %}
        <span class="col-sm-10 offset-sm-2" style="color: red;">[{{ error }}]</span>
        {% endfor %}

    </div>
    <div class="form-group row mb-3">
        {{ form.email.label(class="form-label col-sm-2 col-form-label") }} {{ form.email(class="form-control col") }}</div>
    </div>
    <div class="form-group row mb-3">
        {{ form.role.label(class="form-label col-sm-2 col-form-label") }} {{ form.role(class="form-control col") }}
    </div>
    <div class="row">
        <div class="col"></div>
        <div class="col">
            {{ form.submit(class="btn btn-primary") }}
            <a class="btn btn-secondary" href="{{ url_for('user.list_users') }}">Cancel</a>
        </div>

        <div class="col"></div>
    </div>
</form>
{% endblock %}

computer science/Final Project/project/app/templates/users.html
{% extends "layout.html" %}

{% block title %}
Events
{% endblock %}

{% block main %}
<h1>User List</h1>

<!-- Table of users with view, edit and delete button -->
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.role.name }}</td>
            <td><a class="btn btn-primary" href="{{ url_for('user.view_user', user_id=user.id) }}">View</a>
                <a class="btn btn-secondary" href="{{ url_for('user.edit_user', user_id=user.id) }}">Edit</a>
                <form action="{{ url_for('user.delete_user', user_id=user.id) }}" method="POST"
                    style="display:inline;">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <button class="btn btn-danger" type="submit"
                        onclick="return confirm('Are you sure you want to delete this user?');">Delete</button>
                </form>
            </td>

        </tr>
        {% else %}
        <tr>
            <td>There are no users available.</td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock %}