python web/Project 4/commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/create", views.create_listing, name="create_listing"),
    path("listings/<int:id>", views.listing, name="listing"),
    path("whatchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("category/<int:id>", views.listings_category, name="listings_category"),
    path("error", views.error, name="error"),
    
    path("add_whatchlist/<int:id>", views.add_whatchlist, name="add_whatchlist"),
    path("add_bid/<int:id>", views.add_bid, name="add_bid"),
    path("add_comment/<int:id>", views.add_comment, name="add_comment"),
    path("close_listing/<int:id>", views.close_listing, name="close_listing"),
    
]

python web/Project 4/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

python web/Project 4/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Category(models.Model):
    title = models.CharField(max_length=50)
    image = models.URLField()
    description = models.TextField()

    def __str__(self):
        return f"{self.title}"

class Listing(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    current_bid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    image = models.URLField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.title}"

class Bid(models.Model):
    bid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    bid_time = models.DateTimeField(auto_now_add=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.bidder} bid {self.bid_amount} for {self.listing}"

class Comment(models.Model):
    content = models.TextField()
    comment_time = models.DateTimeField(auto_now_add=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.content[:20]}..."

class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listings = models.ManyToManyField(Listing)

    def __str__(self):
        return f"{self.user} wachlist"

python web/Project 4/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
#from django.model import DoesNotExist
from .models import User, Listing, Bid, Watchlist, Comment, Category


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'description', 'starting_bid', 'category', 'image']

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['bid_amount']
        widgets = {
            'bid_amount': forms.TextInput(attrs={"placeholder": "Bid"})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5})
        }

def index(request):
    active_listings = Listing.objects.filter(is_active=True)
    return render(request, "auctions/index.html", {"active_listings": active_listings})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url ="/login")
def create_listing(request):
    """Before create listig with form input value add user to form instance"""
    form = ListingForm()
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.instance.seller = request.user
            form.instance.current_bid = form.cleaned_data["starting_bid"]
            form.save()

            #return HttpResponseRedirect(reverse("index"))
            form = ListingForm()
            return render(request, 'auctions/create_listing.html', {'form': form, 'create_message':'Listing craeted successfull'})
        else:
            form = ListingForm()
    
    return render(request, 'auctions/create_listing.html', {'form': form})

def listing(request, id):
    try:
        """Get all objects requires for template"""
        listing = Listing.objects.get(id=id)
        comments = Comment.objects.filter(listing=id).order_by('comment_time')
        bidform = BidForm()
        commentform = CommentForm()
        list_bid = Bid.objects.filter(listing=listing).order_by('-bid_time')

        """Build var active_whatchlist. First get user whatchlist."""
        active_whatchlist = False
        if request.user.is_authenticated:
            user = User.objects.get(id=request.user.id)
            user_watchlist = Watchlist.objects.filter(user=user).first()

            """Secod check that user ave instance of whatchlist and check that listings of whatchlist containt the current listing"""
            if user_watchlist:
                if user_watchlist.listings.filter(id=id).count() > 0:
                    active_whatchlist = True

            return render(request, 'auctions/listing.html', {'listing': listing, 'comments':comments, 'list_bid':list_bid, 'active_whatchlist': active_whatchlist, 'bidform': bidform, 'commentform': commentform})
        return render(request, 'auctions/listing.html', {'listing': listing, 'comments':comments,'list_bid':list_bid, 'active_whatchlist': active_whatchlist, 'bidform': bidform, 'commentform': commentform})
    except Listing.DoesNotExist:
        return HttpResponseRedirect(reverse("error"))


@login_required(login_url ="/login")
def add_whatchlist(request, id):
    try:
        if request.user.is_authenticated:
            """Get user whatchlist and check if listings of watchlistig containt the listing."""
            active_whatchlist = False
            user = User.objects.get(id=request.user.id)
            user_watchlist = Watchlist.objects.get(user=user)
            if user_watchlist.listings.filter(id=id).count() > 0:
                active_whatchlist = True

            """If lising is in watchlist remove listing of watchlist. If lising is not in watchlist add listing to watchlist."""
            watchlist, created = Watchlist.objects.get_or_create(user=user)
            listing = Listing.objects.get(id=id)
            if active_whatchlist:
                watchlist.listings.remove(listing)            
            else:
                watchlist.listings.add(listing)

            return HttpResponseRedirect(reverse("listing", args=[id]))
        else:
            return HttpResponseRedirect(reverse("listing", args=[id]))
    except Listing.DoesNotExist:
        return HttpResponseRedirect(reverse("error"))

@login_required(login_url ="/login")
def add_bid(request, id):
    try:
        """Get all objects requires for template"""
        listing = Listing.objects.get(id=id)
        comments = Comment.objects.filter(listing=id).order_by('comment_time')
        bidform = BidForm()
        commentform = CommentForm()

        if request.user.is_authenticated:
            #bid1 = Bid.objects.filter(bidder=request.user.id, listing=listing.id).first()
            #bidform = BidForm(bid1)

            if request.method == 'POST':
                bidform = BidForm(request.POST)
                if bidform.is_valid():
                    """Check that new bid bigger that current bid"""
                    if listing.current_bid < bidform.cleaned_data["bid_amount"]:

                        """Update field current_bid with new form value"""
                        listing.current_bid = bidform.cleaned_data["bid_amount"]
                        listing.save()
                        
                        """Craete new bid"""
                        Bid.objects.create(bidder=request.user, listing=listing, bid_amount=bidform.cleaned_data["bid_amount"])
                    else:
                        error_message = "New value of bid less than current"
                        return render(request, 'auctions/listing.html', {'listing': listing, 'comments':comments,'bidform': bidform, 'commentform': commentform, 'error_message': error_message})

            return HttpResponseRedirect(reverse("listing", args=[id]))
        else:
            return HttpResponseRedirect(reverse("listing", args=[id]))
    except Listing.DoesNotExist:
        return HttpResponseRedirect(reverse("error"))

@login_required(login_url ="/login")
def add_comment(request, id):
    try:
        #bidform = BidForm()
        #comments = Comment.objects.filter(listing=id).order_by('comment_time')

        """Get listing that match with id and create comment related with listing with form value"""
        listing = Listing.objects.get(id=id)
        commentform = CommentForm()
        if request.user.is_authenticated:
            if request.method == 'POST':
                commentform = CommentForm(request.POST)
                if commentform.is_valid():
                    Comment.objects.create(commenter=request.user, listing=listing, content=commentform.cleaned_data["content"])

            #return render(request, 'auctions/listing.html', {'listing': listing, 'comments':comments,'bidform': bidform, 'commentform': commentform})
            return HttpResponseRedirect(reverse("listing", args=[id]))
        else:
            #return render(request, 'auctions/listing.html', {'listing': listing, 'comments':comments,'bidform': bidform, 'commentform': commentform})
            return HttpResponseRedirect(reverse("listing", args=[id]))
    except Listing.DoesNotExist:
        return HttpResponseRedirect(reverse("error"))
        
@login_required(login_url ="/login")
def close_listing(request, id):
    try:
        #comments = Comment.objects.filter(listing=id).order_by('comment_time')
        #bidform = BidForm()
        #commentform = CommentForm()

        if request.user.is_authenticated:
            """Get listing that match with id and change property is_active to False"""
            listing = Listing.objects.get(id=id)
            listing.is_active=False
            listing.save()

            #return render(request, 'auctions/listing.html', {'listing': listing, 'comments':comments,'bidform': bidform, 'commentform': commentform})
            return HttpResponseRedirect(reverse("listing", args=[id]))
        else:
            listing = Listing.objects.get(id=id)

python web/Project 4/commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>

{% for element in list_categories %}
<div class="card list-page" style="margin-bottom: 10px;">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5 col-lg-4">
                {% if element.image %}
                    <image src="{{ element.image}}">
                {% else %}
                    <image src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Medium_box%2C_open.jpg">
                {% endif %}
            </div>
            <div class="col-sm-7 col-lg-8">
                <div>
                    <h4><a href="{%url 'listings_category' element.id%}">{{element.title}}</a></h4>
                </div>
                <div>{{element.description}}</div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="card list-page" style="margin-bottom: 10px;">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5 col-lg-4">
                <image src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Medium_box%2C_open.jpg">
            </div>
            <div class="col-sm-7 col-lg-8">
                <div>
                    <h4><a href="{%url 'listings_category' 0%}">No category</a></h4>
                </div>
                <div></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Create Listings</h2>

{% if create_message %}
<div class="alert alert-info">{{create_message}}</div>
{% endif %}

<form method="post" action="{% url 'create_listing'%}">
    {% csrf_token %}
    <div class="form-group row">
        <div class="col-sm-3  text-right">
            <span>Title:</span>
        </div>
        <div class="col-sm-9">
            {{ form.title}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-3  text-right">
            <span>Description:</span>
        </div>
        <div class="col-sm-9">
            {{ form.description}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-3  text-right">
            <span>Starting bid:</span>
        </div>
        <div class="col-sm-9">
            {{ form.starting_bid}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-3  text-right">
            <span>Category:</span>
        </div>
        <div class="col-sm-9">
            {{ form.category}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-3  text-right">
            <span>Image:</span>
        </div>
        <div class="col-sm-9">
            {{ form.image}}
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3  text-right">
           
        </div>
        <div class="col-sm-9">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>

    
</form>
{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Not found</h2>



<div class="alert alert-danger">
    The requested resource was not found in this server
</div>

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>

{% for element in active_listings %}
<div class="card list-page" style="margin-bottom: 10px;">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5 col-lg-4">
                {% if element.image %}
                    <image src="{{ element.image}}">
                {% else %}
                    <image src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Medium_box%2C_open.jpg">
                {% endif %}
            </div>
            <div class="col-sm-7 col-lg-8">
                <div><h4><a href="{%url 'listing' element.id%}">{{element.title}}</a></h4></div>
                <div><strong>Price: </strong>${{element.current_bid}}</div>
                <div>{{element.description}}</div>
                <div><small class="text-muted">Created {{element.date_created|date:"M. d, Y h:iA"}}</small></div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div>Not listenings actvies</div>
{% endfor %}

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <style>
            img{
                max-height: 300px;
            }

            .list-page img{
                max-width: 300px;
            }

            #id_bid_amount, #id_content{
                width: 100%
            }

            body{
                margin: 15px;
                padding: 0px;
            }
        </style>
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

python web/Project 4/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Show Listing</h2>

<section class="message">
{% if error_message %}
<div class="alert alert-danger">{{error_message}}</div>
{% endif %}

{% if user.is_authenticated and listing.is_active == False and list_bid.0.bidder.id == user.id %}
<div class="alert alert-primary">You won this auction!!!</div>
{% endif %}
</section>

<section class="product">
<div class="row">
    <div class="col-sm-6">
        <h4>Listing: {{ listing.title}}</h4>
    </div>
    <div class="col-sm-6 text-right">
        {% if user.is_authenticated %}
        {% if listing.seller.id == user.id and listing.is_active %}
        <a class="btn btn-danger" href="{% url 'close_listing' listing.id%}">Close Listing</a>
        {% endif%}
        {% endif %}
    </div>

</div>
{% if user.is_authenticated and listing.is_active %}
{% if active_whatchlist %}
<a href="{% url 'add_whatchlist' listing.id%}"><span class="badge badge-primary">Whatchlist</span></a>
{% else %}
<a href="{% url 'add_whatchlist' listing.id%}"><span class="badge badge-secondary">Add Whatchlist</span></a>
{% endif %}
{% else %}
{% if active_whatchlist %}
<span class="badge badge-primary">Whatchlist</span>
{% endif %}
{% endif %}
<div>
    {% if listing.image %}
        <image src="{{ listing.image}}">
    {% else %}
        <image src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Medium_box%2C_open.jpg">
    {% endif %}
        
</div>
<div>
    {{ listing.description}}
</div>
<div>
    <h4>${% if listing.starting_bid >= listing.current_bid %}
        {{listing.starting_bid}}
        {% else %}
        {{listing.current_bid}}
        {% endif %}
    </h4>
</div>
</section>

<section class="form-bid">
{% if user.is_authenticated and listing.is_active %}
<form method="post" action="{% url 'add_bid' listing.id%}">
    {% csrf_token %}
    <div class="form-group row">
        <div class="col-sm-12">
            {% if list_bid|length > 0 %}
            <small>{{list_bid|length}} bid(s) so far.</small>
            {% if list_bid.0.bidder.id == user.id %}
            <small>Your bid is the current bid.</small>
            {% endif %}
            {% else %}
            <small>Be the first to bid.</small>
            {% endif %}
        </div>
        <div class="col-sm-12">
            {{ bidform.bid_amount}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">Place Bid</button>
        </div>
    </div>
</form>
{% endif %}
</section>

<section class="detail">
<div>
    <div class="col-sm-12">
        <strong>Details:</strong>
    </div>
    <ul class="col-sm-12">
        <li>Listed by: {{ listing.seller.username}}</li>
        <li>Category: {% if listing.category %}{{ listing.category.title}}{% else %}No category listed{% endif %}</li>
    </ul>
</div>
</section>

<section class="comments">
{% for element in comments %}
<div class="card" style="margin-bottom: 10px;">
    <div class="card-body" style="padding-bottom: 0px;">
        <div class="row">

            <div class="col-sm-12">
                <div>{{element.content}}</div>
            </div>

        </div>
    </div>
    <div class="text-right" style="padding-right: 10px;">
        <small>By: {{element.commenter.username}} {{element.comment_time|date:"M. d, Y h:iA"}} </small>
    </div>
</div>
{% empty %}
<div class="card" style="margin-bottom: 10px;">
    <div class="card-body">
        <div>Empty Commnets</div>
    </div>
</div>
{% endfor %}

{% if user.is_authenticated and listing.is_active %}
<form method="post" action="{% url 'add_comment' listing.id%}">
    {% csrf_token %}
    <div class="form-group row">
        <div class="col-sm-12">
            <span>Comment:</span>
        </div>
        <div class="col-sm-12">
            {{ commentform.content}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </div>
</form>
{% endif %}
</section>

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/listings_category.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings of category "{% if category %}{{category.title}}{% else %}No category{% endif %}"</h2>

{% for element in listings %}
<div class="card list-page" style="margin-bottom: 10px;">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5 col-lg-4">
                {% if element.image %}
                    <image src="{{ element.image}}">
                {% else %}
                    <image src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Medium_box%2C_open.jpg">
                {% endif %}
            </div>
            <div class="col-sm-7 col-lg-8">
                <div><h4><a href="{%url 'listing' element.id%}">{{element.title}}</a></h4></div>
                <div><strong>Price: </strong>${{element.current_bid}}</div>
                <div>{{element.description}}</div>
                <div><small class="text-muted">Created {{element.date_created|date:"M. d, Y h:iA"}}</small></div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div>Not listings actives</div>
{% endfor %}

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

python web/Project 4/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>User Watchlist</h2>

{% for element in user_watchlist %}
<div class="card list-page" style="margin-bottom: 10px;">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5 col-lg-4">
                {% if element.image %}
                    <image src="{{ element.image}}">
                {% else %}
                    <image src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Medium_box%2C_open.jpg">
                {% endif %}
            </div>
            <div class="col-sm-7 col-lg-8">
                <div><h4><a href="{%url 'listing' element.id%}">{{element.title}}</a></h4></div>
                <div><strong>Price: </strong>${{element.current_bid}}</div>
                <div>{{element.description}}</div>
                <div><small class="text-muted">Created {{element.date_created|date:"M. d, Y h:iA"}}</small></div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div>Empty Watchlist</div>
{% endfor %}

{% endblock %}